name: Snake Game

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: LucasAdrian0
          svg_out_path: dist/github-contribution-grid-snake.gif

      # Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Set output using Environment Files
      - name: Set output using Environment Files
        run: |
          echo "output_name=output_value" >> $GITHUB_ENV
